-- TABLE & SEQUENCE DROP
DROP TABLE BOOK;
DROP SEQUENCE BOOK_SEQ;
DROP TABLE FILEBOARD;
DROP SEQUENCE FILEBOARD_SEQ;
DROP TABLE CUSTOMER;
DROP SEQUENCE CUSTOMER_SEQ;

-- TABLE & SEQUENCE CREATE
CREATE TABLE CUSTOMER(
    cID VARCHAR2(50) PRIMARY KEY,
    cPW VARCHAR2(50) NOT NULL,
    cNAME VARCHAR2(50) NOT NULL,
    cTEL VARCHAR2(50),
    cEMAIL VARCHAR2(50),
    cADDRESS VARCHAR2(250),
    cGENDER VARCHAR2(10),
    cBIRTH DATE,
    cRDATE DATE DEFAULT SYSDATE NOT NULL
);
CREATE SEQUENCE CUSTOMER_SEQ NOCACHE NOCYCLE;

CREATE TABLE FILEBOARD(
    fNUM NUMBER(7,0) PRIMARY KEY,
    cID VARCHAR2(50) REFERENCES CUSTOMER(cID),
    fSUBJECT VARCHAR2(250) NOT NULL,
    fCONTENT VARCHAR2(4000),
    fFILENAME VARCHAR2(50),
    fPW VARCHAR2(50) NOT NULL,
    fHIT NUMBER(7,0) DEFAULT 0 NOT NULL,
    fREF NUMBER(7,0) NOT NULL,
    fRE_STEP NUMBER(7) NOT NULL,
    fRE_LEVEL NUMBER(1) NOT NULL,
    fIP VARCHAR2(50) NOT NULL,
    fRDATE DATE DEFAULT SYSDATE NOT NULL
);
CREATE SEQUENCE FILEBOARD_SEQ NOCACHE NOCYCLE;

CREATE TABLE BOOK(
    bID NUMBER(7,0) PRIMARY KEY,
    bTITLE VARCHAR2(50) NOT NULL,
    bPRICE NUMBER(7) NOT NULL,
    bIMAGE1 VARCHAR2(50) NOT NULL,
    bIMAGE2 VARCHAR2(50) NOT NULL,
    bCONTENT VARCHAR2(4000),
    bDISCOUNT NUMBER(3) NOT NULL,
    bRDATE DATE DEFAULT SYSDATE NOT NULL
);
CREATE SEQUENCE BOOK_SEQ NOCACHE NOCYCLE;

-- 인덱스나 뷰 생성
SELECT * FROM CUSTOMER;
SELECT * FROM FILEBOARD;
SELECT * FROM BOOK;