DROP TABLE BOARD; -- 게시판(MEMBER와 ADMIN 모두 글쓰기 가능)
DROP TABLE ADMIN; -- ADMIN
CREATE TABLE ADMIN(
    aId VARCHAR2(30) PRIMARY KEY,
    aName VARCHAR2(30) NOT NULL);
INSERT INTO ADMIN VALUES ('a1','김관리');
INSERT INTO ADMIN VALUES ('a2','홍관리');
SELECT * FROM ADMIN;
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    mID VARCHAR2(30) PRIMARY KEY,
    mNAME VARCHAR2(30) );
INSERT INTO MEMBER VALUES ('m1','홍멤버');
INSERT INTO MEMBER VALUES ('m2','이멤버');
select * from member;
DROP TABLE BOARD;
CREATE TABLE BOARD(
    bId NUMBER(6) PRIMARY KEY,
    mId VARCHAR2(30) REFERENCES MEMBER(MID),
    aId VARCHAR2(30) REFERENCES ADMIN(aId),
    bTitle VARCHAR2(100) NOT NULL,
    bRdate    DATE DEFAULT SYSDATE,
    bHit     NUMBER(6) DEFAULT 0);
INSERT INTO BOARD values (1, 'm1', null, '제목',sysdate, 0);
INSERT INTO BOARD values (3, 'm2', null, '제목',sysdate, 0);
INSERT INTO BOARD values (2, null, 'a1', '제목',sysdate, 0);
INSERT INTO BOARD values (4, null, 'a2', '제목',sysdate, 0);
select * from board;

SELECT V.*, 
  (SELECT MNAME FROM MEMBER WHERE V.MID=MID) MNAME,
  (SELECT ANAME FROM ADMIN WHERE V.AID=AID) ANAME
  FROM (SELECT ROWNUM RN, B.* 
        FROM (SELECT * FROM BOARD ORDER BY BRDATE DESC) B) V
  WHERE RN BETWEEN 2 AND 4; -- DAO에 들어갈 QUERY : 글쓴이가 MNAME인지 ANAME인지 구분됨
  
SELECT V.*, 
  (SELECT MNAME FROM MEMBER WHERE V.MID=MID) || 
  (SELECT ANAME FROM ADMIN WHERE V.AID=AID) writerName
  FROM (SELECT ROWNUM RN, B.* 
        FROM (SELECT * FROM BOARD ORDER BY BRDATE DESC) B) V
  WHERE RN BETWEEN 2 AND 4; -- cf. 글쓴이가 MNAME인지 ANAME인지 구분되지 않고 글쓴이 이름만
  
  