-- 프로그램 요구사항에 필요한 DML
-- 기능별 query 작성 (1, 2, 3)
INSERT INTO PERSON 
    VALUES (PERSON_NO_SQ.NEXTVAL, '홍길동', (SELECT JNO FROM JOB WHERE JNAME='가수'), 81, 83, 85);

SELECT JNO, JNAME FROM JOB WHERE JNO=30;
-- SELECT PNAME||'('||PNO||'번'||')' 이름, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
--    FROM PERSON P , JOB J WHERE P.JNO=J.JNO
--    ORDER BY SUM DESC;
SELECT ROWNUM RN, A.*
    FROM (SELECT PNAME||'('||PNO||'번'||')' pname, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
        FROM PERSON P , JOB J WHERE P.JNO=J.JNO AND JNAME='배우'
        ORDER BY SUM DESC) A;

SELECT ROWNUM RN, A.*
    FROM (SELECT PNAME||'('||PNO||'번'||')' 이름, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
        FROM PERSON P , JOB J WHERE P.JNO=J.JNO
        ORDER BY SUM DESC) A;

-- 1번과 2번
SELECT JNAME FROM JOB;





