SELECT * FROM TAB;
SELECT * FROM USER_TABLES; -- 내 권한 갖고있는 테이블
SELECT * FROM DBA_TABLES; -- DBA권한만 볼 수 있음
-- 내가 접근할 수 있는 테이블
SELECT * FROM ALL_TABLES
    WHERE TABLE_NAME='EMP';
SELECT * FROM SCOTT.EMP;
SELECT * FROM SCOTT.DEPT; -- 에러(권한부여전)
SELECT * FROM SCOTT.EMP E, SCOTT.DEPT D
    WHERE E.DEPTNO=D.DEPTNO;
EXIT;