-- 시퀀스와 테이블 drop & create
DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_NO_SEQ;
CREATE SEQUENCE FRIEND_NO_SEQ
    NOCACHE
    NOCYCLE;
CREATE TABLE FRIEND (
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(50)
);
SELECT * FROM FRIEND;
INSERT INTO FRIEND VALUES (FRIEND_NO_SEQ.NEXTVAL, '홍길동', '010-9999-9999');
INSERT INTO FRIEND VALUES (FRIEND_NO_SEQ.NEXTVAL, 'ㄴ', '5');
SELECT * FROM FRIEND WHERE FNAME='홍길동';
-- 친구 검색(추후 추가)
SELECT * FROM FRIEND WHERE NAME LIKE '%'||'길'||'%' AND TEL LIKE '%'||'9999'||'%';
COMMIT;